name: Dayflect
description: A memory book to keep all your daily memories.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  url_launcher_web: ^0.1.2
  url_launcher: ^5.5.0
  transparent_image: ^1.0.0
  path: ^1.7.0

dev_dependencies:
  lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/white_logo.png
    - assets/android_read_screenshot.png
    - assets/ios_signin_screenshot.png
    - assets/download_app_store.png
    - assets/download_play_store.png
