name: Dayflect
description: A memory book to keep all your daily memories.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  transparent_image: ^2.0.1
  url_launcher: ^6.3.0
  path: ^1.9.0

dev_dependencies:
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/white_logo.png
    - assets/android_read_screenshot.png
    - assets/ios_signin_screenshot.png
    - assets/download_app_store.png
    - assets/download_play_store.png
